### ISSUE TITLE
Feature Request - Routing for TYPO3 10+

### ISSUE THREAD

**Issue by ineswillenbrock** [nhovratov/jobfair#14]
Hi,

would it be possible to either add an routing example to the docs or "just" add a configuration to the extension?

I searched the web and found an example for the job-views, but not for the application and "back to list" views.
Here the link to the example: https://www.shentao.de/2021/08/typo3-9x-routing-mit-txjobfair-nutzen.html 
(Working fine with TYPO3 11 and jobfair 4.0.4)

I might get back to you with some further rules... might have time this weekend :)

**Comment by nhovratov** [comment]
Hey Ines, you seem very active around this extension, thank you! I don't have so much time to take care of jobfair (I also maintain mask). If you want, I can add you as a maintainer, so you can adjust the docs yourself. I can of course have a glance on your commits and release new versions, when needed.
What do you think?

**Comment by ineswillenbrock** [comment]
Hey, let me think about it and get back to you on Monday? I'm a bit overwhelmed by this suggestion.
It would have to be docs only as my coding skills are (in my opinion) rather on the poorer side

**Comment by nhovratov** [comment]
That would be already helpful. Think about it, I don't expect anything. Every little help is appreciated.

**Comment by ineswillenbrock** [comment]
Ok, I've accepted your request and an example for the routing up and running.
I'll create a branch for the doc-changes.
The older real_url stuff can get lost?
