### ISSUE TITLE
SQL Error: table missing?

### ISSUE THREAD

**Issue by kruechten** [nhovratov/jobfair#4]
Hi , I am trying to set up your extension with FE-Users submitting jobs in TYPO3 10. I created as user und group for this purpose and  followed the manual but when I try to save the job as a logged in frontend user i get an error:

TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException
Table 'wa5237_db4.tx_jobfair_domain_model_user' doesn't exist

I retried in a fresh TYPO3 11 and I have the same problem. As far as I can tell in your code the table tx_jobfair_domain_model_user is not even created on install and I can find no direct reference to it in your code. 

Any ideas and/or help what is going wrong here?

**Comment by nhovratov** [comment]
Hey, yes you are right. I missed to change the persistence classes: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

**Comment by nhovratov** [comment]
I added the migration. Can you check if it works now?

**Comment by kruechten** [comment]
Okay, thanks. The error with "tx_jobfair_domain_model_user" is gone now.  But now when saving a new job I get a different Error:

TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException
Field 'internal_notes' doesn't have a default value

**Comment by nhovratov** [comment]
Thanks for testing!
It seems you have a too strict MySql/MariaDB environment.
Try to disable the strict rules:
`SET GLOBAL SQL_MODE = ''`

**Comment by kruechten** [comment]
Okay, removing the strict rule in the SQL Variable fixes the error und the new job now is saved. This seems to have been a problem in our dev environment (default settings for MySQL in Ubuntu Server 20.04 LTS seem to include the strict rule).  I guess the problem is fixed then as far as I can tell. Thanks for the help.
