### ISSUE TITLE
jobfair 2.0.2 migration problem: Missing "type" in TCA of field

### ISSUE THREAD

**Issue by elosha** [nhovratov/jobfair#7]
Hi, I'm migrating a site from core v8.7 via v9.x to v10.x. Currently on core v8.7.24 (latest) and updated to jobfair v2.0.2 (latest with v8 support). Now I'm getting this:

> Uncaught TYPO3 Exception
> #1482394401: Missing "type" in TCA of field "['tx_jobfair_domain_model_job']['job_image']['config']"
> UnexpectedValueException thrown in file
> /var/www/html/typo3_src-8.7.24/typo3/sysext/core/Classes/Migrations/TcaMigration.php in line 116.

Something I forgot to modify? Thanks!

**Comment by nhovratov** [comment]
Do you have any TCA overrides for the field `job_image` ?

**Comment by elosha** [comment]
@nhovratov Probably my colleague had implemented some. I've asked him and he was able to fix them ;) Thanks for the hint.
